### PR TITLE
120 win images built in gh actions

### PR DESCRIPTION
**Pull request by TCMeldrum**
Please see here for relevant detail: https://github.com/UserOfficeProject/user-office-backend/pull/303

### CODE REVIEW

**Review by martin-trajanovski — APPROVED** [review]

**Review by mr-field — APPROVED** [review]

**Comment by TCMeldrum** [comment]
Does anyone know why the SEP tests might be failing?  I have re-run them one and got the same result, looks like there timing out?

**Comment by martin-trajanovski** [comment]
> Does anyone know why the SEP tests might be failing? I have re-run them one and got the same result, looks like there timing out?

If you open the failing checks and see in the top right corner there is one button called `Artifacts` you can download and see some screenshots from failing tests. Maybe that way you will have better overview why they are failing. Do you try to run the tests locally to see if they pass?

**Comment by TCMeldrum** [comment]
My changes don't change the frontend end just change our dockerfiles and creates a new github action. I don't see why that would change the outcome of the tests. I can try to see if they pass locally.

**Comment by TCMeldrum** [comment]
Re ran the tests and they passed not sure what was happening

**Pull request merged**
