### PR TITLE
refactor(material-ui): Upgrade MUI to v5 and use only luxon for datetime manipulation

### PR DESCRIPTION
**Pull request by martin-trajanovski**
## Description

- Upgrade of `material-ui` from v4 to v5
- Upgraded `@material-table/core` to version compatible with MUI 5.
- Using only `luxon` for datetime manipulation instead of mixing couple of other libraries.
- Using some global theme settings to set default properties on fields instead of repeating on each and every form control.

## Motivation and Context

To be able to use and develop `DateTimeRangePicker` in the future it was recommended to upgrade to MUI 5 because the `material-ui-pickers` package is deprecated(https://github.com/mui-org/material-ui-pickers/issues/2157) and now pickers are part of `@mui/lab` official package.
 
## How Has This Been Tested

- e2e tests
- manual tests

## Fixes

- https://jira.esss.lu.se/browse/SWAP-1937
- https://jira.esss.lu.se/browse/SWAP-2379

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [x] All relevant doc has been updated

### CODE REVIEW

**Comment by martin-trajanovski** [comment]
I am aware that this is a bit hard to review because of the many changes and many files touched. Changes are mainly in import paths and some other standard migration procedures.

**Comment by TCMeldrum** [comment]
Looks good as far as I can see, had a brief look through most of it. Is there anything you would like me to have a closer look at?

**Comment by martin-trajanovski** [comment]
> Looks good as far as I can see, had a brief look through most of it. Is there anything you would like me to have a closer look at?

Not sure at the moment as I mentioned most of the changes are quite standard for this migration. The only bigger thing is with the date/time pickers. I did some more work on those and maybe that could be checked better in sense of logic changes. One more thing that could be useful from reviewers is maybe pulling this locally and try to test it quickly to see if there are any visible differences with the previous version.

**Comment by TCMeldrum** [comment]
Had a look at the refactor side by side with dev and noticed a few things:

When creating a date question some of the validation is no longer there. I don't think  it too big of a deal but might be nice to fix:
image

When inputting a date from the user's side I think it would be good to restrict the date field to numbers and the nice date formating: 
image
Also not sure if I set the question up wrong but that error message seems too "technical" for the user.

Other than that I think the font is slightly bigger in places which I don't think is necessarily a bad thing. 

The rest seems the same from going through our gerenal workflow of the system

**Comment by martin-trajanovski** [comment]
@TCMeldrum I see your point. I will give my best to try to solve this.

**Comment by jekabs-karklins** [comment]
The dropdown in several places is mispositioned with MUI5
too low

**Comment by jekabs-karklins** [comment]
The text input seems to occupy more space
gap

**Comment by jekabs-karklins** [comment]
the select component is higher and for some reason, '%' sign is not as well aligned as it used to be 
adjustments

**Comment by martin-trajanovski** [comment]
@TCMeldrum the things that you mentioned in the comment above are all fixed in the new PR that is an addition of this PR here https://github.com/UserOfficeProject/user-office-frontend/pull/815. Also the error message is fixed in this PR with the validation improvements: https://github.com/UserOfficeProject/user-office-lib/pull/109.

**Comment by martin-trajanovski** [comment]
@jekabs-karklins I will look into these issues they all look valid. Thanks for taking some time testing this.

**Comment by martin-trajanovski** [comment]
> The text input seems to occupy more space gap

Resolved! 🥇 
Screenshot_19

**Comment by martin-trajanovski** [comment]
> the select component is higher and for some reason, '%' sign is not as well aligned as it used to be adjustments

@jekabs-karklins Resolved! ⏬ 🥇 ⏬ 
Screenshot_18

**Comment by martin-trajanovski** [comment]
> The dropdown in several places is mispositioned with MUI5 too low

@jekabs-karklins Resolved ⏬ 🥇 ⏬ 
Screenshot_20

**Review by jekabs-karklins — APPROVED** [review]

**Comment by martin-trajanovski** [comment]
@TCMeldrum I am planning on merging this one today if you are fine with it because it creates lot of merge conflicts when something else is merged.

**Comment by TCMeldrum** [comment]
Yeah, no worries go ahead. Look good!

**Review by TCMeldrum — APPROVED** [review]

**Pull request merged**
