### PR TITLE
197 - Favicon Issue

### PR DESCRIPTION
**Pull request by AspectVI**
## Description

BisAppSettings/Favicon Issue
works with :
isisbusapps/docker-orchestration#174

changes from \\isis\shares\BIS\git\repos\BISAppSettings#197-Favicon_Issue branch will also need to be pulled

Removed favicon from location

## Motivation and Context

Allow for changes to docker orchestration and Kubernetes for the favicon.

## Depends on

This PR works with the following PR "Docker_Orchestration/197 - Favicon issue"

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Comment by TCMeldrum** [comment]
Hi Alex a few things:
- Generally, when we have changes to BisAppSettings we add the BisAppSettings branch name to the PR description and add the BisAppSettings label to both PRs
- Since this affects the ESS as well we need to get thier approval - maybe you can post in the slack about it
- In the future, you will need to follow the [contribution guide](https://github.com/UserOfficeProject/user-office-frontend/blob/develop/CONTRIBUTING.md) for your commits as they are needed to generate release notes

Hope this helps otherwise I am fine with code changes.

Also, there is a way to link to other issues or PR quite nicely in github by using the following format `<orgname>/<repo/project>#<issue number>` e.g. isisbusapps/docker-orchestration#174

**Comment by AspectVI** [comment]
@TCMeldrum I don't have slack no one has set it up for me so how should I tell the ess?

**Comment by TCMeldrum** [comment]
For getting on the slack I think you need to ask Panda about that I think he can get you a link. The PR looks better now although could you add the BisAppSetting branch name and on the Docker Orchestration PR as there isn't a github repo for it since it is hosted internally. 

However, it seems with Cosimo's suggested changing this PR doesn't actually make any code changes in this repo so can we close this PR without merging?  Sorry about getting you to make those changes to the PR for there to end up being no code changes.

**Comment by AspectVI** [comment]
I will be closing this PR as it is no longer relevant see following PR for a solution to Issue

https://github.com/isisbusapps/docker-orchestration/pull/174

**Pull request closed without merging**
