### PR TITLE
SWAP-1162 Factory e2e

### PR DESCRIPTION
**Pull request by peter-asztalos**
## Description

e2e tests are updated to use the new PDF factory.

## Motivation and Context

The old version is removed, we need to test the new version.

## How Has This Been Tested

Tested with e2e tests.

## Fixes

https://jira.esss.lu.se/browse/SWAP-1162

## Changes

- e2e docker compose updated

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by martin-trajanovski — APPROVED** [review]

**Comment by martin-trajanovski** [comment]
@peter-asztalos are you using the same tests that were for the old pdf generation because I can not see any new e2e tests here? You have mentioned something about checking and testing the content of the pdfs is that something to come or it is hard to implement?

**Comment by peter-asztalos** [comment]
That test will be part of the factory, not the FE e2e tests.

**Comment by martin-trajanovski** [comment]
> That test will be part of the factory, not the FE e2e tests.

OK good to know.

**Review by jekabs-karklins — APPROVED** [review]

**Comment by peter-asztalos** [comment]
@UserOfficeProject/stfc-business-apps

**Review by mr-field — APPROVED** [review]

**Pull request merged**
