### PR TITLE
Replace old code with EXTERNAL_AUTH

### PR DESCRIPTION
**Pull request by AlbertoPaulPopescu**
Closes https://github.com/UserOfficeProject/stfc-user-office-project/issues/137

@simonfernandes helped me make the routes as a component so it can be used inside the FeatureContextProvider to access the EXTERNAL_AUTH. Thank you!

Tests:
Tested the changes for normal login onto the new ESS system using external authentication - works ✔
Tested the changes for normal login onto the new ESS system using external authentication and after removing the environment variables locally from docker-compose in docker orchestration (see below) ✔
image

This fix should allow @mr-field to continue your work.

## Depends on (merge-together)

This PR depends on https://github.com/isisbusapps/docker-orchestration/pull/129 for removing environment variables from docker-orchestration files.

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by ACLay — COMMENTED** [review]
Do we need anything to enable the external auth feature for our environment? Or has that already been done in a separate PR?

**Comment by AlbertoPaulPopescu** [comment]
@ACLay There is another PR that was merged which has the EXTERNAL_AUTH feature enabled in the DB. Although, I am not sure if that is what you are asking about? After merging these two PRs it should require no further code changes to be able to login in the ESS app: https://github.com/UserOfficeProject/user-office-frontend/pull/447 isisbusapps/docker-orchestration#129

**Review by ACLay — APPROVED** [review]
>There is another PR that was merged which has the EXTERNAL_AUTH feature enabled in the DB. Although, I am not sure if that is what you are asking about?

Yeah, that's what I wanted to check :+1:

**Review by mr-field — APPROVED** [review]

**Review by jekabs-karklins — APPROVED** [review]

**Comment by simonfernandes** [comment]
Sorry, yes, I was going to comment for you to remove it and then thought I could just make the change myself. In the other PR you have removed the variables from being used when the image is run, and the lines I removed were for when it's built.

**Comment by AlbertoPaulPopescu** [comment]
> Sorry, yes, I was going to comment for you to remove it and then thought I could just make the change myself. In the other PR you have removed the variables from being used when the image is run, and the lines I removed were for when it's built.

@simonfernandes  Thank you, it appears to have solved the built problems in the github tests too, I think? :)

**Comment by simonfernandes** [comment]
I think it was just coincidence! Looks good to merge now 👍

**Pull request merged**
